namespace YoutubeV2.Features.Video.Models;

public sealed class CaptionTrackInfo
{
    public required string Language { get; init; }
    public required string LanguageName { get; init; }
    public required bool IsAutoGenerated { get; init; }
    public required string Url { get; init; }
} 